# Generated by Django 3.2.9 on 2022-01-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('Geo_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrahealth.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Have_you_lost_smell_or_test', models.BooleanField()),
                ('Do_you_have_a_sore_throat', models.BooleanField()),
                ('Are_you_experiencing_fatigue', models.BooleanField()),
                ('Do_you_have_a_cough', models.BooleanField()),
                ('Do_you_have_difficulties_in_breathing', models.BooleanField()),
                ('Do_you_have_a_fever', models.BooleanField()),
                ('Do_you_have_chills', models.BooleanField()),
                ('Do_you_have_a_headache', models.BooleanField()),
                ('Do_you_have_muscle_aches', models.BooleanField()),
                ('Do_you_have_nasal_congestion', models.BooleanField()),
                ('Are_you_experiencing_nausea', models.BooleanField()),
                ('Are_you_experiencing_any_vomiting', models.BooleanField()),
                ('Do_you_have_diarrhea', models.BooleanField()),
                ('Close_contact_with_an_infected_person', models.BooleanField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrahealth.patient')),
            ],
        ),
    ]
