# Generated by Django 3.2.9 on 2022-01-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0002_auto_20220125_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice',
            field=models.CharField(max_length=5),
        ),
    ]
