# Generated by Django 3.2.9 on 2022-01-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0004_rename_choices_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
