# Generated by Django 3.2.9 on 2022-01-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0006_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='today',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
