# Generated by Django 3.2.9 on 2022-01-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0008_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
