# Generated by Django 3.2.9 on 2022-01-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0009_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.BooleanField(),
        ),
    ]
