# Generated by Django 3.2.9 on 2022-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0013_auto_20220126_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='recommendation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
