# Generated by Django 3.2.9 on 2022-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0014_medicaltest_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
