# Generated by Django 3.2.9 on 2022-01-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0016_auto_20220128_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date_tested',
            new_name='date_responded',
        ),
    ]
