# Generated by Django 3.2.9 on 2022-02-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrahealth', '0017_rename_date_tested_answer_date_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='patient',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrahealth.answer'),
        ),
    ]
