# Generated by Django 3.2.9 on 2022-02-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0017_rename_date_tested_answer_date_responded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='patient',
        ),
    ]
