# Generated by Django 3.2.9 on 2022-02-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0018_remove_answer_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='infrahealth.patient'),
            preserve_default=False,
        ),
    ]
