# Generated by Django 3.2.9 on 2022-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrahealth', '0019_answer_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_responded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='date_tested',
            field=models.DateField(auto_now=True),
        ),
    ]
